POST http://127.0.0.1:5000/user/add
Content-Type: application/json

{
    "nom" : "nous"
}

###

GET http://127.0.0.1:5000/users

###

GET  http://127.0.0.1:5000/users/1
#Content-Type: application/json

#{
#    "id" : "1"
#}